update README according to ExportBehavior

diff --git a/.github/workflows/build-deploy.yml b/.github/workflows/build-deploy.yml
--- a/.github/workflows/build-deploy.yml
+++ b/.github/workflows/build-deploy.yml
@@ -26,7 +26,12 @@ jobs:
         echo "GAME_DIR=$GAME_DIR" >> $GITHUB_OUTPUT
         echo "GAME_NAME=$GAME_NAME" >> $GITHUB_OUTPUT
     - name: Exit Check
-      run: if [[ $GAME_DIR = Error:* ]]; then exit 1; fi
+      run: |
+        if [[ $GAME_DIR = Error:* ]]
+        then
+          echo "::error::$GAME_DIR"
+          exit 1;
+        fi
 
   export-web:
     needs: find_export_game
@@ -56,11 +61,10 @@ jobs:
       - name: Godot Web Build
         run: |
           ./scripts/export.sh $GAME_DIR
-      - name: Move game_info.json and thumbnail
+      - name: Move game_info.json and thumbnail.png
         run: |
           if [ -f ${GAME_DIR}/game_info.json ]; then mv ${GAME_DIR}/game_info.json build/web/game_info.json; fi
           if [ -f ${GAME_DIR}/thumbnail.png ]; then mv ${GAME_DIR}/thumbnail.png build/web/thumbnail.png; fi
-          if [ -f ${GAME_DIR}/thumbnail.jpg ]; then mv ${GAME_DIR}/thumbnail.jpg build/web/thumbnail.jpg; fi
       - name: Patch for Cross Origin Isolation and SharedArrayBuffer
         run: |
           mv scripts/enable-threads.js build/web/enable-threads.js
